#!/bin/fish
set input_file $argv[1]
cat $input_file > tmp
perl -0777 -ne ' 
    my $first = 1; 
    while (/module\s+(\S[\s\S]*?\))/g) { 
        my $module = $1; 

        if ($first) { 
            $first = 0; 
            next; 
        } 

        $module =~ s/input/./g; 
        $module =~ s/output/\@output\@/g; 
        $module =~ s/^module\s+//; 
        $module =~ s/\s//g; 
        $module =~ s/\)/()\);/g; 
        $module =~ s/,/(),/g; 
        print "$module
"; 
    } 
' tmp | sed 's/\@output\@/%/' > tmp2; 

perl -0777 -ne ' 
    s/output/./g; 
    s/%/ \/\*<-i | o->\*\/ ./g; 
    s/\@//g; 
    print $_; 
' tmp2 | sed -E "s/.(\[[0-9:]+\])([^\(]+)\(\)/.\2()\/\*\1\*\/ /g" > tmp
cat tmp2 | sed -E 's/^([A-Za-z_0-9$]+)\(.*/\1/g'>>tmp
rm tmp2



